name: Build and Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: install packages
        run: npm install
      - name: build
        run: npm run compile
      - name: lint
        run: npm run lint
      - name: Test
        run: npm run test
